x-frontend-variables: &frontend-variables
  environment:
    NG_APP_API_URL: http://localhost:3002

version: '3.1'
services:
  frontend:
    build: ./
    ports:
      - 3000:3000
    restart: always  
    <<: *frontend-variables